name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          version: "0.5.2"
      - name: Test
        shell: bash
        run: make test
      - uses: taobojlen/croissant-action@v0
        with:
          hostname: croissant.btao.workers.dev
          files: "testresults.xml"
